export enum EstadoClad {
  BORRADOR = 'BORRADOR',
  ENVIADO_DPTO = 'ENVIADO_DPTO',
  OBSERVADO_DPTO = 'OBSERVADO_DPTO',
  VALIDADO_DPTO = 'VALIDADO_DPTO',
  OBSERVADO_DEPENDENCIA = 'OBSERVADO_DEPENDENCIA',
  VALIDADO_DEPENDENCIA = 'VALIDADO_DEPENDENCIA',
  APROBADO_FINAL = 'APROBADO_FINAL'
}
