export enum EstadoDeclaracionCarga {
  BORRADOR = "BORRADOR",
  ENVIADO = "ENVIADO",
  OBSERVADO_DPTO = "OBSERVADO_DPTO",
  VALIDADO_DPTO = "VALIDADO_DPTO",
  OBSERVADO_FACULTAD = "OBSERVADO_FACULTAD",
  APROBADO_FACULTAD = "APROBADO_FACULTAD",
  CERRADO = "CERRADO",
  REABIERTO = "REABIERTO",
}
