export enum ModalidadDocente {
  DEDICACION_EXCLUSIVA = 'DEDICACION_EXCLUSIVA',
  TIEMPO_COMPLETO_40   = 'TIEMPO_COMPLETO_40',
  TIEMPO_PARCIAL_20    = 'TIEMPO_PARCIAL_20',
  TIEMPO_PARCIAL_12    = 'TIEMPO_PARCIAL_12',
  TIEMPO_PARCIAL_10    = 'TIEMPO_PARCIAL_10',
  TIEMPO_PARCIAL_8     = 'TIEMPO_PARCIAL_8',
}
