export enum TipoActividadNoLectiva {
  PREPARACION_EVALUACION = "PREPARACION_EVALUACION",
  INVESTIGACION = "INVESTIGACION",
  TUTORIA = "TUTORIA",
  GESTION_ACADEMICA = "GESTION_ACADEMICA",
  PROYECCION_SOCIAL = "PROYECCION_SOCIAL",
  CAPACITACION = "CAPACITACION",
  OTRA = "OTRA",
}
