export enum TipoDependenciaClad {
  POSGRADO = 'POSGRADO',
  SEGUNDA_ESPECIALIDAD = 'SEGUNDA_ESPECIALIDAD',
  CEPUNT = 'CEPUNT',
  FILIAL = 'FILIAL',
  CENTRO_PRODUCCION = 'CENTRO_PRODUCCION',
  OTRO = 'OTRO'
}
