FROM node:18-alpine AS builder

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build -- --configuration=production

FROM nginx:alpine AS production

RUN apk add --no-cache curl

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/frontend/dist/frontend/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
