module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testMatch: [
    '**/*.spec.ts',
    '**/*.e2e-spec.ts',
  ],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.spec.(t|j)s',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/entities/**',
    '!src/migrations/**',
  ],
  coverageDirectory: './coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@auth/(.*)$': '<rootDir>/src/auth/$1',
    '^@cursos/(.*)$': '<rootDir>/src/cursos/$1',
    '^@docentes/(.*)$': '<rootDir>/src/docentes/$1',
    '^@grupos/(.*)$': '<rootDir>/src/grupos/$1',
    '^@horarios/(.*)$': '<rootDir>/src/horarios/$1',
    '^@disponibilidad/(.*)$': '<rootDir>/src/disponibilidad/$1',
    '^@ventanas/(.*)$': '<rootDir>/src/ventanas/$1',
    '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
    '^@reportes/(.*)$': '<rootDir>/src/reportes/$1',
    '^@notificaciones/(.*)$': '<rootDir>/src/notificaciones/$1',
  },
  coverageThreshold: {
    global: {
      branches: 10,
      functions: 10,
      lines: 10,
      statements: 10,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  testTimeout: 30000,
  projects: [
    {
      displayName: 'unit',
      testMatch: ['<rootDir>/src/**/*.spec.ts'],
      transform: {
        '^.+\\.(t|j)s$': 'ts-jest',
      },
      moduleFileExtensions: ['js', 'json', 'ts'],
      collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.spec.(t|j)s',
        '!src/**/*.module.ts',
        '!src/main.ts',
        '!src/entities/**',
        '!src/migrations/**',
      ],
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@common/(.*)$': '<rootDir>/src/common/$1',
        '^@auth/(.*)$': '<rootDir>/src/auth/$1',
        '^@cursos/(.*)$': '<rootDir>/src/cursos/$1',
        '^@docentes/(.*)$': '<rootDir>/src/docentes/$1',
        '^@grupos/(.*)$': '<rootDir>/src/grupos/$1',
        '^@horarios/(.*)$': '<rootDir>/src/horarios/$1',
        '^@disponibilidad/(.*)$': '<rootDir>/src/disponibilidad/$1',
        '^@ventanas/(.*)$': '<rootDir>/src/ventanas/$1',
        '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
        '^@reportes/(.*)$': '<rootDir>/src/reportes/$1',
        '^@notificaciones/(.*)$': '<rootDir>/src/notificaciones/$1',
      },
    },
    {
      displayName: 'integration',
      testMatch: ['<rootDir>/test/integration/**/*.e2e-spec.ts'],
      testEnvironment: 'node',
      setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
      transform: {
        '^.+\\.(t|j)s$': 'ts-jest',
      },
      moduleFileExtensions: ['js', 'json', 'ts'],
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@common/(.*)$': '<rootDir>/src/common/$1',
        '^@auth/(.*)$': '<rootDir>/src/auth/$1',
        '^@cursos/(.*)$': '<rootDir>/src/cursos/$1',
        '^@docentes/(.*)$': '<rootDir>/src/docentes/$1',
        '^@grupos/(.*)$': '<rootDir>/src/grupos/$1',
        '^@horarios/(.*)$': '<rootDir>/src/horarios/$1',
        '^@disponibilidad/(.*)$': '<rootDir>/src/disponibilidad/$1',
        '^@ventanas/(.*)$': '<rootDir>/src/ventanas/$1',
        '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
        '^@reportes/(.*)$': '<rootDir>/src/reportes/$1',
        '^@notificaciones/(.*)$': '<rootDir>/src/notificaciones/$1',
      },
      maxWorkers: 1,
    },
  ],
};
