
import { Repository } from "typeorm";
import { PlanEstudios } from "../entities/plan-estudios.entity";
import { CursoPlanEstudios } from "../entities/curso-plan-estudios.entity";
import { Curso } from "../entities/curso.entity";
import { Grupo } from "../entities/grupo.entity";
import { TipoClase } from "../common/enums/tipo-clase.enum";
import { Escuela } from "../entities/escuela.entity";
import { PeriodoAcademico } from "../entities/periodo-academico.entity";

export async function seedPlanEstudios(
  planRepo: Repository<PlanEstudios>,
  cursoRepo: Repository<Curso>,
  cursoPlanRepo: Repository<CursoPlanEstudios>,
  grupoRepo: Repository<Grupo>,
  escuela: Escuela,
  periodoActivo: PeriodoAcademico
) {
  // 1. Crear Plan de Estudios 2018
  const plan2018 = await planRepo.save(
    planRepo.create({
      codigo: "2018",
      nombre: "Plan de Estudios 2018",
      descripcion:
        "Plan de estudios de Ingeniería de Sistemas - Aprobado con R.N° 123-2018-UNT",
      resolucion: "R.N° 123-2018-UNT",
      anio: 2018,
      activo: true,
      escuela_id: escuela.id,
    })
  );
  console.log("✅ Plan de Estudios 2018 creado");

  // 2. Datos de Cursos
  const cursosData = [
    // Ciclo I
    {
      codigo: "I-101",
      nombre: "Introducción a la Programación",
      creditos: 4,
      ht: 2,
      hp: 0,
      hl: 4,
      ciclo: 1,
      lab: true,
    },
    {
      codigo: "I-102",
      nombre: "Introducción a la Ingeniería de Sistemas",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    {
      codigo: "I-103",
      nombre: "Desarrollo Personal",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    {
      codigo: "I-104",
      nombre: "Desarrollo del Pensamiento Lógico Matemático",
      creditos: 4,
      ht: 3,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    {
      codigo: "I-105",
      nombre: "Lectura Crítica y Redacción de Textos Académicos",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    {
      codigo: "I-106",
      nombre: "Introducción al Análisis Matemático",
      creditos: 4,
      ht: 3,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    {
      codigo: "I-107",
      nombre: "Estadística General",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 1,
      lab: false,
    },
    // Ciclo II
    {
      codigo: "II-201",
      nombre: "Programación Orientada a Objetos I",
      creditos: 4,
      ht: 2,
      hp: 0,
      hl: 4,
      ciclo: 2,
      lab: true,
    },
    {
      codigo: "II-202",
      nombre: "Cálculo I",
      creditos: 4,
      ht: 3,
      hp: 2,
      hl: 0,
      ciclo: 2,
      lab: false,
    },
    {
      codigo: "II-203",
      nombre: "Álgebra Lineal",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 2,
      lab: false,
    },
    {
      codigo: "II-204",
      nombre: "Comunicación Integral",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 2,
      lab: false,
    },
    // Ciclo III
    {
      codigo: "III-301",
      nombre: "Programación Orientada a Objetos II",
      creditos: 4,
      ht: 2,
      hp: 0,
      hl: 4,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-302",
      nombre: "Sistémica",
      creditos: 3,
      ht: 2,
      hp: 1,
      hl: 2,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-303",
      nombre: "Ingeniería Gráfica",
      creditos: 3,
      ht: 1,
      hp: 1,
      hl: 3,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-304",
      nombre: "Matemática Aplicada",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-305",
      nombre: "Estadística Aplicada",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-306",
      nombre: "Administración General",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 3,
      lab: false,
    },
    {
      codigo: "III-307",
      nombre: "Física Electrónica",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 3,
      lab: true,
    },
    {
      codigo: "III-308",
      nombre: "Psicología Organizacional",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 3,
      lab: false,
    },
    // Ciclo IV
    {
      codigo: "IV-401",
      nombre: "Estructuras de Datos",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 4,
      lab: true,
    },
    {
      codigo: "IV-402",
      nombre: "Ecuaciones Diferenciales",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 4,
      lab: false,
    },
    {
      codigo: "IV-403",
      nombre: "Matemática Discreta",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 4,
      lab: false,
    },
    // Ciclo V
    {
      codigo: "V-501",
      nombre: "Ingeniería de Datos I",
      creditos: 4,
      ht: 2,
      hp: 1,
      hl: 3,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-502",
      nombre: "Sistemas de Información",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 5,
      lab: false,
    },
    {
      codigo: "V-503",
      nombre: "Transformación Digital",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-504",
      nombre: "Tecnologías Web",
      creditos: 3,
      ht: 1,
      hp: 1,
      hl: 3,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-505",
      nombre: "Arquitectura y Organización de Computadoras",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-506",
      nombre: "Teleinformática",
      creditos: 3,
      ht: 1,
      hp: 2,
      hl: 2,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-507",
      nombre: "Investigación de Operaciones",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 5,
      lab: true,
    },
    {
      codigo: "V-508",
      nombre: "Contabilidad Gerencial",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 5,
      lab: true,
    },
    // Ciclo VI
    {
      codigo: "VI-601",
      nombre: "Sistemas Operativos",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 6,
      lab: true,
    },
    {
      codigo: "VI-602",
      nombre: "Redes de Computadoras",
      creditos: 4,
      ht: 2,
      hp: 0,
      hl: 4,
      ciclo: 6,
      lab: true,
    },
    {
      codigo: "VI-603",
      nombre: "Ingeniería de Software II",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 6,
      lab: false,
    },
    // Ciclo VII
    {
      codigo: "VII-701",
      nombre: "Ingeniería del Software I",
      creditos: 3,
      ht: 2,
      hp: 1,
      hl: 3,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-702",
      nombre: "Redes y Comunicaciones I",
      creditos: 4,
      ht: 2,
      hp: 2,
      hl: 3,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-703",
      nombre: "Negocios Electrónicos",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-704",
      nombre: "Gestión de Servicios de TI",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-705",
      nombre: "Metodología de la Investigación Científica",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 7,
      lab: false,
    },
    {
      codigo: "VII-706",
      nombre: "Administración de Base de Datos",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 3,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-707",
      nombre: "Planeamiento Estratégico de la Información",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 7,
      lab: true,
    },
    {
      codigo: "VII-708",
      nombre: "Cadena de Suministros",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 7,
      lab: false,
    },
    // Ciclo VIII
    {
      codigo: "VIII-801",
      nombre: "Seguridad Informática",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 8,
      lab: true,
    },
    {
      codigo: "VIII-802",
      nombre: "Inteligencia Artificial",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 8,
      lab: true,
    },
    {
      codigo: "VIII-803",
      nombre: "Auditoría de Sistemas",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 0,
      ciclo: 8,
      lab: false,
    },
    // Ciclo IX
    {
      codigo: "IX-901",
      nombre: "Tesis I",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-902",
      nombre: "Analítica de Negocios",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-903",
      nombre: "Auditoría Informática",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 2,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-904",
      nombre: "Gestión de Proyectos de TI",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 3,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-905",
      nombre: "Emprendimiento Tecnológico",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-906",
      nombre: "Ingeniería Web",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 3,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-907",
      nombre: "Computación en la Nube",
      creditos: 3,
      ht: 2,
      hp: 2,
      hl: 3,
      ciclo: 9,
      lab: true,
    },
    {
      codigo: "IX-908",
      nombre: "Hackeo Ético",
      creditos: 3,
      ht: 2,
      hp: 0,
      hl: 2,
      ciclo: 9,
      lab: true,
    },
    // Ciclo X
    {
      codigo: "X-1001",
      nombre: "Proyecto de Tesis II",
      creditos: 4,
      ht: 2,
      hp: 4,
      hl: 0,
      ciclo: 10,
      lab: false,
    },
    {
      codigo: "X-1002",
      nombre: "Ética Profesional",
      creditos: 2,
      ht: 1,
      hp: 2,
      hl: 0,
      ciclo: 10,
      lab: false,
    },
    {
      codigo: "X-1003",
      nombre: "Legislación Informática",
      creditos: 2,
      ht: 1,
      hp: 2,
      hl: 0,
      ciclo: 10,
      lab: false,
    },
  ];

  // 3. Crear Cursos
  const dbCursos: Curso[] = [];
  for (const c of cursosData) {
    const curso = await cursoRepo.save(
      cursoRepo.create({
        codigo: c.codigo,
        nombre: c.nombre,
        creditos: c.creditos,
        horas_teoria: c.ht,
        horas_practica: c.hp,
        horas_laboratorio: c.hl,
        ciclo: c.ciclo,
        tiene_laboratorio: c.lab,
        activo: true,
      })
    );
    dbCursos.push(curso);
  }
  console.log(`✅ ${dbCursos.length} cursos creados`);

  // 4. Crear CursoPlanEstudios (asignar cursos al plan)
    for (const curso of dbCursos) {
      await cursoPlanRepo.save(
        cursoPlanRepo.create({
          plan_estudios_id: plan2018.id,
          curso_id: curso.id,
          ciclo: curso.ciclo,
          tipo_curso: "OBLIGATORIO_GENERAL",
          horas_teoria: curso.horas_teoria,
          horas_practica: curso.horas_practica,
          horas_laboratorio: curso.horas_laboratorio,
          creditos: curso.creditos,
          estado: "ACTIVO",
        })
      );
    }
  console.log("✅ Cursos asignados al Plan de Estudios 2018");

  // 5. Crear Grupos
  const dbGrupos: Grupo[] = [];
  for (const curso of dbCursos) {
    const numGrupos = curso.horas_laboratorio > 0 ? 2 : 1;
    for (let g = 1; g <= numGrupos; g++) {
      const grupo = await grupoRepo.save(
        grupoRepo.create({
          codigo: `${curso.codigo}-G${g}`,
          nombre: `${curso.nombre} - Grupo ${g}`,
          ciclo: curso.ciclo,
          cupo_maximo: 30,
          periodo_academico_id: periodoActivo.id,
          curso_id: curso.id,
          tipo: curso.tiene_laboratorio ? TipoClase.LABORATORIO : TipoClase.TEORIA,
        })
      );
      dbGrupos.push(grupo);
    }
  }
  console.log(`✅ ${dbGrupos.length} grupos creados`);

  return { plan2018, cursos: dbCursos, grupos: dbGrupos };
}
